### ISSUE TITLE
Attribute Audit Explorer Export File not saving

### ISSUE THREAD

**Issue by stapix** [MarioEME/MESquare.XrmToolBox.AuditExplorer#4]
Every single time I try to export the file from the plugin, there is no file saved.

**Comment by MicioGatto** [comment]
Same issue here.  There is no feedback on progress or any indication that something has gone wrong.

If I change the max parallel threads to 1, then the yellow 'Exporting to Excel' progress window remains. but no indication that anything is actually working.

This is for a query for a single field on a single entity for a single author over just 4 days.

**Comment by JulienReny** [comment]
I have the same issue. I see the file in Recent, but when i click on it, it says it's deleted and the size is 0.
![2019-09-03_9-56-18](https://user-images.githubusercontent.com/24722507/64186475-e7925f80-ce3c-11e9-9207-aa06c433e923.png)

**Comment by MarioEME** [comment]
Hey guys,
First let me apologize for the late response, but I didn't notice this messages until yesterday.
I've tested the export feature and detected the issue. I'll try and fix it in the next days. I'll let you know If more information is needed.

**Comment by MarioEME** [comment]
Fixed in version 1.2019.9.2
